//package com.bob.okio.processor;
//
//import org.greenrobot.eventbus.meta.SimpleSubscriberInfo;
//import org.greenrobot.eventbus.meta.SubscriberMethodInfo;
//import org.greenrobot.eventbus.meta.SubscriberInfo;
//import org.greenrobot.eventbus.meta.SubscriberInfoIndex;
//
//import org.greenrobot.eventbus.ThreadMode;
//
//import java.util.HashMap;
//import java.util.Map;
//
///** This class is generated by EventBus, do not edit. */
//public class DemoMyEventBusIndex implements SubscriberInfoIndex {
//    private static final Map<Class<?>, SubscriberInfo> SUBSCRIBER_INDEX;
//
//    static {
//        SUBSCRIBER_INDEX = new HashMap<Class<?>, SubscriberInfo>();
//
//        putIndex(new SimpleSubscriberInfo(com.bob.executor.Main2Activity.class, true, new SubscriberMethodInfo[] {
//                new SubscriberMethodInfo("onMainEvent", String.class),
//                new SubscriberMethodInfo("onMainEvent2", Integer.class),
//        }));
//
//        putIndex(new SimpleSubscriberInfo(com.bob.executor.MainActivity.class, true, new SubscriberMethodInfo[] {
//                new SubscriberMethodInfo("onMainEvent", String.class),
//                new SubscriberMethodInfo("onMainEvent2", Integer.class),
//        }));
//
//    }
//
//    private static void putIndex(SubscriberInfo info) {
//        SUBSCRIBER_INDEX.put(info.getSubscriberClass(), info);
//    }
//
//    @Override
//    public SubscriberInfo getSubscriberInfo(Class<?> subscriberClass) {
//        SubscriberInfo info = SUBSCRIBER_INDEX.get(subscriberClass);
//        if (info != null) {
//            return info;
//        } else {
//            return null;
//        }
//    }
//}
